// Generated by gencpp from file second_pack/Do_ItResponse.msg
// DO NOT EDIT!


#ifndef SECOND_PACK_MESSAGE_DO_ITRESPONSE_H
#define SECOND_PACK_MESSAGE_DO_ITRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_pack
{
template <class ContainerAllocator>
struct Do_ItResponse_
{
  typedef Do_ItResponse_<ContainerAllocator> Type;

  Do_ItResponse_()
    : result(0)  {
    }
  Do_ItResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::second_pack::Do_ItResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_pack::Do_ItResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Do_ItResponse_

typedef ::second_pack::Do_ItResponse_<std::allocator<void> > Do_ItResponse;

typedef boost::shared_ptr< ::second_pack::Do_ItResponse > Do_ItResponsePtr;
typedef boost::shared_ptr< ::second_pack::Do_ItResponse const> Do_ItResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_pack::Do_ItResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_pack::Do_ItResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_pack::Do_ItResponse_<ContainerAllocator1> & lhs, const ::second_pack::Do_ItResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_pack::Do_ItResponse_<ContainerAllocator1> & lhs, const ::second_pack::Do_ItResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_pack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_pack::Do_ItResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_pack::Do_ItResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_pack::Do_ItResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_pack::Do_ItResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_pack::Do_ItResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_pack::Do_ItResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_pack::Do_ItResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::second_pack::Do_ItResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::second_pack::Do_ItResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_pack/Do_ItResponse";
  }

  static const char* value(const ::second_pack::Do_ItResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_pack::Do_ItResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"int64 result\n"
;
  }

  static const char* value(const ::second_pack::Do_ItResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_pack::Do_ItResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Do_ItResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_pack::Do_ItResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_pack::Do_ItResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_PACK_MESSAGE_DO_ITRESPONSE_H
