// Generated by gencpp from file second_pack/Do_ItRequest.msg
// DO NOT EDIT!


#ifndef SECOND_PACK_MESSAGE_DO_ITREQUEST_H
#define SECOND_PACK_MESSAGE_DO_ITREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_pack
{
template <class ContainerAllocator>
struct Do_ItRequest_
{
  typedef Do_ItRequest_<ContainerAllocator> Type;

  Do_ItRequest_()
    : a(0)
    , b(0)  {
    }
  Do_ItRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::second_pack::Do_ItRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_pack::Do_ItRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Do_ItRequest_

typedef ::second_pack::Do_ItRequest_<std::allocator<void> > Do_ItRequest;

typedef boost::shared_ptr< ::second_pack::Do_ItRequest > Do_ItRequestPtr;
typedef boost::shared_ptr< ::second_pack::Do_ItRequest const> Do_ItRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_pack::Do_ItRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_pack::Do_ItRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_pack::Do_ItRequest_<ContainerAllocator1> & lhs, const ::second_pack::Do_ItRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_pack::Do_ItRequest_<ContainerAllocator1> & lhs, const ::second_pack::Do_ItRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_pack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_pack::Do_ItRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_pack::Do_ItRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_pack::Do_ItRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_pack::Do_ItRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_pack::Do_ItRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_pack::Do_ItRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_pack::Do_ItRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::second_pack::Do_ItRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::second_pack::Do_ItRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_pack/Do_ItRequest";
  }

  static const char* value(const ::second_pack::Do_ItRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_pack::Do_ItRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::second_pack::Do_ItRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_pack::Do_ItRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Do_ItRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_pack::Do_ItRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_pack::Do_ItRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_PACK_MESSAGE_DO_ITREQUEST_H
