// Generated by gencpp from file second_pack/Do_It.msg
// DO NOT EDIT!


#ifndef SECOND_PACK_MESSAGE_DO_IT_H
#define SECOND_PACK_MESSAGE_DO_IT_H

#include <ros/service_traits.h>


#include <second_pack/Do_ItRequest.h>
#include <second_pack/Do_ItResponse.h>


namespace second_pack
{

struct Do_It
{

typedef Do_ItRequest Request;
typedef Do_ItResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Do_It
} // namespace second_pack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::second_pack::Do_It > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::second_pack::Do_It&) { return value(); }
};

template<>
struct DataType< ::second_pack::Do_It > {
  static const char* value()
  {
    return "second_pack/Do_It";
  }

  static const char* value(const ::second_pack::Do_It&) { return value(); }
};


// service_traits::MD5Sum< ::second_pack::Do_ItRequest> should match
// service_traits::MD5Sum< ::second_pack::Do_It >
template<>
struct MD5Sum< ::second_pack::Do_ItRequest>
{
  static const char* value()
  {
    return MD5Sum< ::second_pack::Do_It >::value();
  }
  static const char* value(const ::second_pack::Do_ItRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_pack::Do_ItRequest> should match
// service_traits::DataType< ::second_pack::Do_It >
template<>
struct DataType< ::second_pack::Do_ItRequest>
{
  static const char* value()
  {
    return DataType< ::second_pack::Do_It >::value();
  }
  static const char* value(const ::second_pack::Do_ItRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::second_pack::Do_ItResponse> should match
// service_traits::MD5Sum< ::second_pack::Do_It >
template<>
struct MD5Sum< ::second_pack::Do_ItResponse>
{
  static const char* value()
  {
    return MD5Sum< ::second_pack::Do_It >::value();
  }
  static const char* value(const ::second_pack::Do_ItResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_pack::Do_ItResponse> should match
// service_traits::DataType< ::second_pack::Do_It >
template<>
struct DataType< ::second_pack::Do_ItResponse>
{
  static const char* value()
  {
    return DataType< ::second_pack::Do_It >::value();
  }
  static const char* value(const ::second_pack::Do_ItResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SECOND_PACK_MESSAGE_DO_IT_H
