// Generated by gencpp from file first_pack/multipleResponse.msg
// DO NOT EDIT!


#ifndef FIRST_PACK_MESSAGE_MULTIPLERESPONSE_H
#define FIRST_PACK_MESSAGE_MULTIPLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first_pack
{
template <class ContainerAllocator>
struct multipleResponse_
{
  typedef multipleResponse_<ContainerAllocator> Type;

  multipleResponse_()
    : result(0)  {
    }
  multipleResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::first_pack::multipleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_pack::multipleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct multipleResponse_

typedef ::first_pack::multipleResponse_<std::allocator<void> > multipleResponse;

typedef boost::shared_ptr< ::first_pack::multipleResponse > multipleResponsePtr;
typedef boost::shared_ptr< ::first_pack::multipleResponse const> multipleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_pack::multipleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_pack::multipleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first_pack::multipleResponse_<ContainerAllocator1> & lhs, const ::first_pack::multipleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first_pack::multipleResponse_<ContainerAllocator1> & lhs, const ::first_pack::multipleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first_pack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first_pack::multipleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_pack::multipleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_pack::multipleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_pack::multipleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_pack::multipleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_pack::multipleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_pack::multipleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::first_pack::multipleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::first_pack::multipleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_pack/multipleResponse";
  }

  static const char* value(const ::first_pack::multipleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_pack::multipleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Output/Response\n"
"int32 result\n"
;
  }

  static const char* value(const ::first_pack::multipleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_pack::multipleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multipleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_pack::multipleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first_pack::multipleResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_PACK_MESSAGE_MULTIPLERESPONSE_H
