// Generated by gencpp from file first_pack/multipleRequest.msg
// DO NOT EDIT!


#ifndef FIRST_PACK_MESSAGE_MULTIPLEREQUEST_H
#define FIRST_PACK_MESSAGE_MULTIPLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first_pack
{
template <class ContainerAllocator>
struct multipleRequest_
{
  typedef multipleRequest_<ContainerAllocator> Type;

  multipleRequest_()
    : a(0)
    , b(0)  {
    }
  multipleRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::first_pack::multipleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_pack::multipleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct multipleRequest_

typedef ::first_pack::multipleRequest_<std::allocator<void> > multipleRequest;

typedef boost::shared_ptr< ::first_pack::multipleRequest > multipleRequestPtr;
typedef boost::shared_ptr< ::first_pack::multipleRequest const> multipleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_pack::multipleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_pack::multipleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first_pack::multipleRequest_<ContainerAllocator1> & lhs, const ::first_pack::multipleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first_pack::multipleRequest_<ContainerAllocator1> & lhs, const ::first_pack::multipleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first_pack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first_pack::multipleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_pack::multipleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_pack::multipleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_pack::multipleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_pack::multipleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_pack::multipleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_pack::multipleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8322123148e475e3e93a1f609b2f70";
  }

  static const char* value(const ::first_pack::multipleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8322123148e475ULL;
  static const uint64_t static_value2 = 0xe3e93a1f609b2f70ULL;
};

template<class ContainerAllocator>
struct DataType< ::first_pack::multipleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_pack/multipleRequest";
  }

  static const char* value(const ::first_pack::multipleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_pack::multipleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Inputs/Request\n"
"int32 a\n"
"int32 b\n"
;
  }

  static const char* value(const ::first_pack::multipleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_pack::multipleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multipleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_pack::multipleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first_pack::multipleRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_PACK_MESSAGE_MULTIPLEREQUEST_H
