// Generated by gencpp from file first_pack/multiple.msg
// DO NOT EDIT!


#ifndef FIRST_PACK_MESSAGE_MULTIPLE_H
#define FIRST_PACK_MESSAGE_MULTIPLE_H

#include <ros/service_traits.h>


#include <first_pack/multipleRequest.h>
#include <first_pack/multipleResponse.h>


namespace first_pack
{

struct multiple
{

typedef multipleRequest Request;
typedef multipleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiple
} // namespace first_pack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::first_pack::multiple > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::first_pack::multiple&) { return value(); }
};

template<>
struct DataType< ::first_pack::multiple > {
  static const char* value()
  {
    return "first_pack/multiple";
  }

  static const char* value(const ::first_pack::multiple&) { return value(); }
};


// service_traits::MD5Sum< ::first_pack::multipleRequest> should match
// service_traits::MD5Sum< ::first_pack::multiple >
template<>
struct MD5Sum< ::first_pack::multipleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::first_pack::multiple >::value();
  }
  static const char* value(const ::first_pack::multipleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_pack::multipleRequest> should match
// service_traits::DataType< ::first_pack::multiple >
template<>
struct DataType< ::first_pack::multipleRequest>
{
  static const char* value()
  {
    return DataType< ::first_pack::multiple >::value();
  }
  static const char* value(const ::first_pack::multipleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::first_pack::multipleResponse> should match
// service_traits::MD5Sum< ::first_pack::multiple >
template<>
struct MD5Sum< ::first_pack::multipleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::first_pack::multiple >::value();
  }
  static const char* value(const ::first_pack::multipleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_pack::multipleResponse> should match
// service_traits::DataType< ::first_pack::multiple >
template<>
struct DataType< ::first_pack::multipleResponse>
{
  static const char* value()
  {
    return DataType< ::first_pack::multiple >::value();
  }
  static const char* value(const ::first_pack::multipleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRST_PACK_MESSAGE_MULTIPLE_H
